apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: stocks-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: cloudacademydevops/stocks-api:v2
        ports:
        - containerPort: 8080
        env:
        - name: DB_CONNSTR
          value: "jdbc:mysql://db-service:3306/stocks"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "secret123"
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: stocks-namespace
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001  
  selector:
    app: api