apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.app.image }}
        ports:
        - containerPort: 8080
        env:
        - name: REACT_APP_APIHOSTPORT
          value: {{ .Values.app.apiHostPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace.name }}
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: {{ .Values.app.nodePort }}
  selector:
    app: frontend
